# Whitelist some Domains
huggingface.co ollama.com r-ccs27.riken.jp {
    # Docker's DNS server accessible to all containers at 127.0.0.11:53
    forward . 127.0.0.11
}

# DNS Sinkhole for everything else
. {
    acl {
        block
    }
    ## resolve everything to NXDOMAIN
    #template ANY ANY {
    #    rcode NXDOMAIN
    #}
    ## log errors to standard out
    #errors
    ## for better verification, we add logging of all requests
    #log
}
